### ISSUE TITLE
Doesn't let files open in windows 10 when you click on the files in file explorer

### ISSUE THREAD

**Issue by MachinaeWolf** [rossy/mpv-install#8] opened 2017-03-15 15:30 UTC
I told it to open the files it should be associated with it after running the install batch file as admin and instead of opening the files it just keeps asking me what I want to run it with. I hit ok I want to run it with the path to mpv and it just pops up again and again until I quit.

**Comment by MachinaeWolf** [comment] 2017-03-15 16:52
Ok so as a workaround it does work fine if you run it in compatibility mode for windows 7 :)

**Comment by rossy** [comment] 2017-07-20 00:01
Sorry, I forgot about this issue. I'm not sure what would be causing it, since I develop and test this script on Windows 10 as well. I can't reproduce it, so it's possible that it's a temporary bug that's been fixed in Windows. As such, I'm tentatively closing this issue. Feel free to re-open if you can still reproduce it in the latest build of Windows 10 (Creators Update version 1703.)

**Closed as completed by rossy** 2017-07-20 00:01 UTC
